# Generated by Django 2.1.1 on 2018-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_country', models.CharField(max_length=50)),
                ('home_colour', models.CharField(max_length=50)),
            ],
        ),
    ]
